import pandas as pd
import argparse

def scanning_log_to_sparsity_dict_template(input_file: str, output_file: str):
    df = pd.read_csv(input_file)
    df = df[['name', 'recommand_sparsity']].rename(columns={'recommand_sparsity': 'sparsity'})
    df.to_csv(output_file, index=False)

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert scanning_log to sparsity_dict_template.")
    parser.add_argument("--f", type=str, help="Path to `scanning_log.csv` generated by sensitivity_scan")
    parser.add_argument("--o", type=str, default="sparsity_dict_template.csv", help="Filename of output file")
    
    args = parser.parse_args()
    scanning_log_to_sparsity_dict_template(args.f, args.o)
